services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERN://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERN://broker:29092
      KAFKA_ADVERTISED_LISTENERS: EXTERN://192.168.0.125:9092,CONTROLLER://localhost:9093,INTERN://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERN:PLAINTEXT,INTERN:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8008:8000'
    command:
      - start 
      - --log=trace
      - --user=root 
      - --pass=root
    healthcheck:
      test: ["CMD", "isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s 
      start_interval: 5s
  web_server:
    image: backend_http:latest
    ports:
      - '8001:8000'
    environment:
      PY_LOGGER: debug
      PY_KAFKA_HOST: broker
      PY_KAFKA_PORT: 9092
      PY_KAFKA_TOPICS: testTopic
      PY_SURREAL_HOST: surrealdb
      PY_SURREAL_PORT: 8000
      PY_SURREAL_USER: root
      PY_SURREAL_PASS: root
      PY_SURREAL_NAMESPACE: test
      PY_SURREAL_DB: test
      PY_SURREAL_TABLE: requests
      CONNECTOR_API_KEY: $OPENAI_KEY
      CONNECTOR_MODEL_NAME: ft:gpt-4o-mini-2024-07-18:scg:docstrings:BEnEMYz9
    healthcheck:
      test: ["CMD", "curl", "http://localhost/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s
      start_interval: 10s
    depends_on:
      - surrealdb
  llm_dispatcher:
    image: llm_dispatcher:latest
    ports:
      - 8002:8000
    environment:
      SURREAL_HOST: 192.168.0.125:8008
      SURREAL_NAMESPACE: test
      SURREAL_DATABASE: test
      SURREAL_USER: root
      SURREAL_PASS: root
      SURREAL_TABLE: requests
      KAFKA_HOST: broker:9092
      KAFKA_TOPICS: testTopic
      KAFKA_GROUP_ID: abcgroup
      LAZY_LOAD: false
      RUST_LOG: debug,rdkafka=trace,rust_llm_dispatcher=trace
      PATH: /usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      RUSTUP_HOME: /usr/local/rustup
      CARGO_HOME: /usr/local/cargo
      RUST_VERSION: 1.86.0
    depends_on:
      - surrealdb
      - web_server
    volumes:
      - llm_cache:/root/.cache
volumes:
  llm_cache:
